import { ThemeToggle } from './ThemeToggle';

interface SignInScreenProps {
  signIn: () => void;
}

export function SignInScreen({ signIn }: SignInScreenProps) {
  return (
    <div className="sign-in-screen">
      <ThemeToggle />
      <div className="sign-in-container">
        <h1>🌍 World Knowledge Trivia</h1>
        <p className="subtitle">
          Test your knowledge with AI-generated trivia questions from around the world!
        </p>

        <div className="features">
          <div className="feature">
            <span className="feature-icon">🤖</span>
            <h3>AI-Powered Questions</h3>
            <p>Unlimited unique questions generated by advanced AI</p>
          </div>
          <div className="feature">
            <span className="feature-icon">🏆</span>
            <h3>Track Your Progress</h3>
            <p>Save your scores and compete with yourself</p>
          </div>
          <div className="feature">
            <span className="feature-icon">🌐</span>
            <h3>Multiple Categories</h3>
            <p>Geography, history, culture, science, and more</p>
          </div>
        </div>

        <button className="sign-in-button" onClick={signIn}>
          Sign In to Play
        </button>

        <p className="info-text">
          Sign in to save your progress and access unlimited AI-generated trivia questions
        </p>
      </div>
    </div>
  );
}
